# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags: []
  skip-dirs:
    - vendor
    - bin
    - artifacts
  skip-files:
    - ".*_test\\.go$"
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Go vet
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - typecheck     # Type checking
    - unused        # Check for unused code
    - gofmt         # Check formatting
    - goimports     # Check imports
    - misspell      # Check for spelling mistakes
    - gocritic      # Go critique
    - revive        # Fast linter
    - gosec         # Security issues
    - bodyclose     # Check HTTP response body close
    - dupl          # Duplicate code detection
    - exportloopref # Check loop variable references
    - nilerr        # Find nil error checks
    - prealloc      # Find slice declarations that could be preallocated
    - unconvert     # Remove unnecessary type conversions

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/workshop/cicd-demo
  
  misspell:
    locale: US
  
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: indent-error-flow
        severity: warning
  
  gosec:
    excludes:
      - G404  # Use of weak random number generator (for demos)
  
  dupl:
    threshold: 100

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - errcheck

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
